// <auto-generated />
using DataService.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

namespace DataService.Migrations
{
    [DbContext(typeof(GothamContext))]
    [Migration("20210123113717_initialDB")]
    partial class initialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityByDefaultColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 63)
                .HasAnnotation("ProductVersion", "5.0.2");

            modelBuilder.Entity("DataService.Entities.Admin", b =>
                {
                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Email");

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Email = "abcd@gmail.com",
                            Password = "abcd"
                        },
                        new
                        {
                            Email = "efgh@gmail.com",
                            Password = "efgh"
                        },
                        new
                        {
                            Email = "ijkl@gmail.com",
                            Password = "ijkl"
                        });
                });

            modelBuilder.Entity("DataService.Entities.Outlet", b =>
                {
                    b.Property<int>("OutletId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Date")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FoodPackets")
                        .HasColumnType("integer");

                    b.Property<int>("FoodType")
                        .HasColumnType("integer");

                    b.Property<string>("Landmark")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<int>("RequiredVolunteers")
                        .HasColumnType("integer");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("OutletId");

                    b.ToTable("Outlets");

                    b.HasData(
                        new
                        {
                            OutletId = 1,
                            Date = "21/01/2020",
                            FoodPackets = 78,
                            FoodType = 1,
                            Landmark = "ABC Store",
                            Name = "Rose",
                            RequiredVolunteers = 7,
                            Street = "ABC"
                        },
                        new
                        {
                            OutletId = 2,
                            Date = "22/01/2020",
                            FoodPackets = 100,
                            FoodType = 0,
                            Landmark = "DEF Store",
                            Name = "Lily",
                            RequiredVolunteers = 10,
                            Street = "DEF"
                        },
                        new
                        {
                            OutletId = 3,
                            Date = "23/01/2020",
                            FoodPackets = 110,
                            FoodType = 2,
                            Landmark = "GHI Store",
                            Name = "Jasmine",
                            RequiredVolunteers = 11,
                            Street = "GHI"
                        },
                        new
                        {
                            OutletId = 4,
                            Date = "24/01/2020",
                            FoodPackets = 200,
                            FoodType = 2,
                            Landmark = "JKL Store",
                            Name = "Lavender",
                            RequiredVolunteers = 20,
                            Street = "JKL"
                        },
                        new
                        {
                            OutletId = 5,
                            Date = "25/01/2020",
                            FoodPackets = 400,
                            FoodType = 0,
                            Landmark = "MNO Store",
                            Name = "Orchid",
                            RequiredVolunteers = 40,
                            Street = "MNO"
                        });
                });

            modelBuilder.Entity("DataService.Entities.Volunteers", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .UseIdentityByDefaultColumn();

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("OutletId")
                        .HasColumnType("integer");

                    b.Property<long>("Phone")
                        .HasColumnType("bigint");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("OutletId");

                    b.ToTable("Volunteers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Muhsina",
                            OutletId = 1,
                            Phone = 86066244485L,
                            email = "muhsinabinthabdulla@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Hepzibha",
                            OutletId = 2,
                            Phone = 98204928902L,
                            email = "Hepzibha@gmail.com"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Priya",
                            OutletId = 3,
                            Phone = 5864564025L,
                            email = "Prya@gmail.com"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Megha",
                            OutletId = 4,
                            Phone = 89208374890L,
                            email = "Megha@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Navneeth",
                            OutletId = 5,
                            Phone = 9820328902L,
                            email = "FantomPhreak@gmail.com"
                        });
                });

            modelBuilder.Entity("DataService.Entities.Volunteers", b =>
                {
                    b.HasOne("DataService.Entities.Outlet", "Outlet")
                        .WithMany()
                        .HasForeignKey("OutletId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Outlet");
                });
#pragma warning restore 612, 618
        }
    }
}
